### ISSUE TITLE
Centos 6.5 Python 2.7.9 use pyv8-linux64.zip fail

### ISSUE THREAD

**Issue by alexming** [emmetio/pyv8-binaries#24]
Python 2.7.9 (default, Mar  9 2016, 10:11:52) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-16)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import PyV8
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "PyV8.py", line 32, in <module>
    import _PyV8
ImportError: ./_PyV8.so: undefined symbol: PyUnicodeUCS4_FromEncodedObject

**Comment by bluebad** [comment]
Me too. Centos 7.2 Python 2.7.11

**Comment by yejun0218** [comment]
Me too. Centos 6.6 Python 2.7.9
