### ISSUE TITLE
How to install PyV8 in windows platform?

### ISSUE THREAD

**Issue by xnchall** [emmetio/pyv8-binaries#35]
python version is python3.6.5, and i want to install PyV8 in windows 10.

i have got two files, such as PyV8.py, _PyV8.pyd. and put them into site-packages on my computer.
but, there some mistake, they are:
`>>> import PyV8
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\software\python\lib\site-packages\PyV8.py", line 32, in <module>
    import _PyV8
ModuleNotFoundError: No module named '_PyV8'`

i have tried lot's of ways to solve them, but usless.

thx a lot ~ @sergeche @mindofmicah @Chikuid

**Comment by Dashu-Xu** [comment]
hi,
have you solve this problem yet?
i meet the same problem now but don't know how to fix it.

**Comment by xnchall** [comment]
@Dashu-Xu it's depressing， pyV8 support py2+ on windows series, py3 nonsupport :(
if you want use pyV8 by py3+, you can select linux series platform.

**Comment by pandaeyes1** [comment]
me too,bro

**Comment by sunendran** [comment]
me too same problem. does anyone try in Linux platform?  did that work in Linux os?

**Comment by sergeche** [comment]
This plugin (as well as PyV8) is deprecated, try new, upcoming Emmet 2 version, which is 100% Python codebase: https://github.com/emmetio/sublime-text-plugin

**Comment by SameKingSton** [comment]
move _PyV8.py file into "D:\software\python\lib\site-packages\" Than go on , but python3.6+ no suit It, Module use of python33.dll conflicts with this version of Python.
