### ISSUE TITLE
The error of importing PyV8

### ISSUE THREAD

**Issue by EdQzz** [emmetio/pyv8-binaries#36]
>>> import PyV8
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/python3/lib/python3.7/site-packages/PyV8.py", line 32, in <module>
    import _PyV8
ImportError: /usr/local/python3/lib/python3.7/site-packages/_PyV8.so: undefined symbol: _PyThreadState_Current
>>>

Centos 7.4 
Python3,7
pyv8-linux64-p3.zip

How could I deal with this problem

**Comment by XMISSM** [comment]
Do you slove it? I meet the same error.
