### ISSUE TITLE
can not imort _PyV8

### ISSUE THREAD

**Issue by Mararesliu** [emmetio/pyv8-binaries#37]
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 125, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/Users/marares/Library/Application Support/Sublime Text 3/Packages/pyv8-osx-p3/PyV8.py", line 32, in <module>
    import _PyV8
ImportError: No module named '_PyV8'

os: 10.15.1
sumlime text 3

**Comment by Mararesliu** [comment]
donwload pvy8 to packages may not a right way, I use default way to install emmet, the pyv8 installed right when network is good. I guess Default way may compile the .so file by the OSX
